apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-prod
  labels:
    cmtype: nginx
data:
  server.conf: |
    server {
      listen 80 default_server;
      location / {
        proxy_pass http://127.0.0.1:8080/;
      }
    }

